import { useEffect, useRef, useState } from "react";
import Editor, { type OnMount } from "@monaco-editor/react";
import type { editor } from "monaco-editor";

import { Button } from "@/components/common/Button";
import { useTableViewStore } from "@/stores/tableViewStore";
import { runSqlWithConfirm } from "@/lib/sql";
import { FOCUS_SQL_EVENT } from "@/lib/events";
import "@/lib/monaco"; // side effect: configure offline Monaco workers

const PLACEHOLDER = "-- Select a table, or write SQL here and press ⌘/Ctrl+Enter";

/**
 * Always-visible SQL panel. It shows the SQL generated by the visual browser and
 * also lets the user edit that SQL and run it directly (⌘/Ctrl+Enter or "Run").
 * Editing detaches the editor from the generated SQL; "Reset" re-syncs it.
 */
export function SqlPreview() {
  const generatedSql = useTableViewStore((s) => s.sql);
  const loading = useTableViewStore((s) => s.loading);
  const error = useTableViewStore((s) => s.error);
  const notice = useTableViewStore((s) => s.notice);

  const [draft, setDraft] = useState(generatedSql);
  const [dirty, setDirty] = useState(false);
  const [copied, setCopied] = useState(false);

  // Keep a live ref to the draft so the editor's keybinding (registered once on
  // mount) always runs the latest text rather than a stale closure.
  const draftRef = useRef(draft);
  draftRef.current = draft;

  const editorRef = useRef<editor.IStandaloneCodeEditor | null>(null);

  // While the user hasn't manually edited, mirror the generated SQL.
  useEffect(() => {
    if (!dirty) setDraft(generatedSql);
  }, [generatedSql, dirty]);

  // Focus the editor on the global "focus SQL" shortcut (⌘/Ctrl+L).
  useEffect(() => {
    const focus = () => editorRef.current?.focus();
    window.addEventListener(FOCUS_SQL_EVENT, focus);
    return () => window.removeEventListener(FOCUS_SQL_EVENT, focus);
  }, []);

  const run = async () => {
    const sql = draftRef.current.trim();
    if (!sql || sql === PLACEHOLDER) return;
    await runSqlWithConfirm(sql);
  };

  const reset = () => {
    setDraft(generatedSql);
    setDirty(false);
  };

  const copy = async () => {
    if (!draft) return;
    await navigator.clipboard.writeText(draft);
    setCopied(true);
    setTimeout(() => setCopied(false), 1200);
  };

  const onMount: OnMount = (instance, monaco) => {
    editorRef.current = instance;
    instance.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.Enter, () => {
      void run();
    });
  };

  const canRun = !loading && draft.trim().length > 0 && draft.trim() !== PLACEHOLDER;

  return (
    <div className="flex h-full flex-col border-l border-border">
      <div className="flex h-8 shrink-0 items-center gap-2 border-b border-border bg-surface px-3">
        <span className="text-2xs font-semibold uppercase tracking-wide text-muted">
          SQL {dirty && <span className="text-accent">• edited</span>}
        </span>
        <div className="ml-auto flex items-center gap-1.5">
          {dirty && (
            <Button variant="ghost" onClick={reset} disabled={loading}>
              Reset
            </Button>
          )}
          <Button variant="ghost" onClick={() => void copy()} disabled={!draft}>
            {copied ? "Copied" : "Copy"}
          </Button>
          <Button onClick={() => void run()} disabled={!canRun} title="Run (⌘/Ctrl+Enter)">
            {loading ? "Running…" : "Run"}
          </Button>
        </div>
      </div>

      <div className="min-h-0 flex-1">
        <Editor
          height="100%"
          language="sql"
          theme="vs-dark"
          value={draft || PLACEHOLDER}
          onChange={(value) => {
            setDraft(value ?? "");
            setDirty((value ?? "") !== generatedSql);
          }}
          onMount={onMount}
          options={{
            readOnly: false,
            minimap: { enabled: false },
            fontSize: 13,
            lineNumbers: "on",
            scrollBeyondLastLine: false,
            wordWrap: "on",
            padding: { top: 8 },
            renderLineHighlight: "line",
            overviewRulerLanes: 0,
            scrollbar: { vertical: "auto", horizontal: "auto" },
          }}
        />
      </div>

      {(error || notice) && (
        <div
          className={`shrink-0 border-t px-3 py-1.5 text-2xs ${
            error
              ? "border-red-500/30 bg-red-500/10 text-red-300"
              : "border-border bg-surface text-muted"
          }`}
        >
          {error ?? notice}
        </div>
      )}
    </div>
  );
}
